name: open_container
description: Container transform animation.
version: 1.0.1
homepage: https://github.com/danielgorka/open_container

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
